#Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###


# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

#Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name" : "Sala de teste",
    "description" : "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

#Create question
# @name createQuestion
POST {{baseUrl}}/rooms/0b01fdac-7fe8-4f25-9dad-8d69104ca471/questions
Content-Type: application/json

{
    "question" : "O que é React?"
}